version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=4 twit_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
    ports:
      - "8000"
    env_file:
      - ./.env.prod
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:13.11
    env_file:
      - ./.env.db.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume: