# Generated by Django 4.2 on 2023-05-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_created_add_reply_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'Твит', 'verbose_name_plural': 'Твиты'},
        ),
    ]
